/**
 * Created by energizer on 22.03.17.
 */

export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const CHANGE_FILTER = 'CHANGE_FILTER';

export const REQUEST_USERS_STATISTICS = 'REQUEST_USERS_STATISTICS';
export const RECEIVE_USERS_STATISTICS = 'RECEIVE_USERS_STATISTICS';

export const REQUEST_MESSAGES_STATISTICS = 'REQUEST_MESSAGES_STATISTICS';
export const RECEIVE_MESSAGES_STATISTICS = 'RECEIVE_MESSAGES_STATISTICS';
